FROM python:3.7.9

WORKDIR /app

RUN pip install requests==2.26.0 SQLAlchemy==1.3.24 PyMySQL==0.9.3 itsdangerous==1.1.0 certifi==2020.6.20 click==7.1.2 Flask==1.1.4 Jinja2==2.11.2 joblib==0.17.0 MarkupSafe==1.1.1 numpy==1.19.3 pandas==1.1.4 scikit-learn==0.23.2 scipy==1.5.3 sklearn==0.0

ENTRYPOINT ["python"]

CMD ["app.py"]

